name: Testing pipeline

on: [push, pull_request]

jobs:
  testing-process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Clean install
      run: npm ci
    - name: Testing process
      run: npm test